export const suggestionsData = {
  actors: [
    {
      adult: false,
      gender: 0,
      id: 1479299,
      known_for: [
        {
          adult: false,
          backdrop_path: "/boW5pAd6jJsmzcIise5JPk2tNtK.jpg",
          genre_ids: [10752, 18],
          id: 89132,
          media_type: "movie",
          original_language: "en",
          original_title: "Ambush Bay",
          overview:
            "A Marine unit on a Japanese-held island in the Philippines tries to hook up with local Filipino guerrillas.",
          poster_path: "/aHbgOhYvHNoBxT0f6ZSA4X4zQrT.jpg",
          release_date: "1966-05-10",
          title: "Ambush Bay",
          video: false,
          vote_average: 4.6,
          vote_count: 5,
        },
      ],
      known_for_department: "Writing",
      media_type: "person",
      name: "Marve Feinberg",
      popularity: 0.6,
      profile_path: null,
    },
  ],
  movies: [
    {
      adult: false,
      backdrop_path: "/w2PMyoyLU22YvrGK3smVM9fW1jj.jpg",
      genre_ids: [28, 12, 878],
      id: 299537,
      media_type: "movie",
      original_language: "en",
      original_title: "Captain Marvel",
      overview:
        "The story follows Carol Danvers as she becomes one of the universe’s most powerful heroes when Earth is caught in the middle of a galactic war between two alien races. Set in the 1990s, Captain Marvel is an all-new adventure from a previously unseen period in the history of the Marvel Cinematic Universe.",
      popularity: 205.461,
      poster_path: "/AtsgWhDnHTq68L0lLsUrCnM7TjG.jpg",
      release_date: "2019-03-06",
      title: "Captain Marvel",
      video: false,
      vote_average: 7,
      vote_count: 10970,
    },
    {
      adult: false,
      backdrop_path: "/69GY219MYBurtf8joA2okEa3x8I.jpg",
      genre_ids: [99],
      id: 787923,
      media_type: "movie",
      original_language: "en",
      original_title: "Marvel's Behind the Mask",
      overview:
        "A documentary special that explores the power of identity behind the iconic superheroes we know and love today. These legendary Marvel creations and stories have not only reflected the world outside our window – they have become a reflection of our own identities and who we truly are.",
      popularity: 101.128,
      poster_path: "/p71YgDQk5sFHTqF3FBygLPmZEX5.jpg",
      release_date: "2021-02-12",
      title: "Marvel's Behind the Mask",
      video: false,
      vote_average: 8.3,
      vote_count: 15,
    },
    {
      adult: false,
      backdrop_path: "/iGtSJbDku0riOw1joO1qD4pGwdm.jpg",
      genre_ids: [28, 12, 878, 14, 9648],
      id: 609681,
      media_type: "movie",
      original_language: "en",
      original_title: "Captain Marvel 2",
      overview: "The sequel to Captain Marvel (2019).",
      popularity: 54.212,
      poster_path: "/gWxeVJ920nprJEbXbzmuuzeaAar.jpg",
      release_date: "2022-11-10",
      title: "Captain Marvel 2",
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: "/3sffou4UaLTpQHtocLBg8Egw5Uq.jpg",
      genre_ids: [878, 28, 14],
      id: 119569,
      media_type: "movie",
      original_language: "en",
      original_title: "Marvel One-Shot: Item 47",
      overview:
        "Benny and Claire, a down on their luck couple find a discarded Chitauri gun, referred to as 'Item 47'...",
      popularity: 27.184,
      poster_path: "/rfxvoRoZtBLUXJqLf8z9kgJWkKt.jpg",
      release_date: "2012-09-13",
      title: "Marvel One-Shot: Item 47",
      video: false,
      vote_average: 6.5,
      vote_count: 281,
    },
    {
      adult: false,
      backdrop_path: "/gpeWMh3rzbTn9auEZO6TLIzaMVl.jpg",
      genre_ids: [28, 12, 878, 14],
      id: 211387,
      media_type: "movie",
      original_language: "en",
      original_title: "Marvel One-Shot: Agent Carter",
      overview:
        "The film takes place one year after the events of Captain America: The First Avenger, in which Agent Carter, a member of the Strategic Scientific Reserve, is in search of the mysterious Zodiac.",
      popularity: 23.059,
      poster_path: "/5WOxsdb6uF9cDZ319Kdcru2C0eC.jpg",
      release_date: "2013-09-08",
      title: "Marvel One-Shot: Agent Carter",
      video: false,
      vote_average: 7.4,
      vote_count: 442,
    },
    {
      adult: false,
      backdrop_path: "/hP6lCsOfOEQv1Mh2by79I64DBeI.jpg",
      genre_ids: [28, 12, 878, 16],
      id: 284019,
      media_type: "movie",
      original_language: "en",
      original_title: "Phineas and Ferb: Mission Marvel",
      overview:
        "When Dr. Doofenshmirtz's latest invention causes the Marvel heroes to lose their powers, they team up with Phineas and Ferb to save the world from Doofenshmirtz and the Marvel villains.",
      popularity: 15.407,
      poster_path: "/da2AREjdecPInHzWeZ550X1aYDU.jpg",
      release_date: "2013-08-16",
      title: "Phineas and Ferb: Mission Marvel",
      video: false,
      vote_average: 6.7,
      vote_count: 109,
    },
  ],
  shows: [
    {
      backdrop_path: "/iqmJfU6DkqJra9PqIepaOJbzfa1.jpg",
      first_air_date: "2021-01-08",
      genre_ids: [99],
      id: 114695,
      media_type: "tv",
      name: "Marvel Studios: Legends",
      origin_country: ["US"],
      original_language: "en",
      original_name: "Marvel Studios: Legends",
      overview:
        "Revisit the epic heroes, villains and moments from across the MCU in preparation for the stories still to come. Each dynamic segment feeds directly into the upcoming series — setting the stage for future events. This series weaves together the many threads that constitute the unparalleled Marvel Cinematic Universe.",
      popularity: 455.569,
      poster_path: "/EpDuYIK81YtCUT3gH2JDpyj8Qk.jpg",
      vote_average: 7.7,
      vote_count: 320,
    },
    {
      backdrop_path: "/80BRASQnT9KT7BkFeEI0EdeRIF3.jpg",
      first_air_date: "2013-09-24",
      genre_ids: [18, 10765, 10759],
      id: 1403,
      media_type: "tv",
      name: "Marvel's Agents of S.H.I.E.L.D.",
      origin_country: ["US"],
      original_language: "en",
      original_name: "Marvel's Agents of S.H.I.E.L.D.",
      overview:
        "Agent Phil Coulson of S.H.I.E.L.D. (Strategic Homeland Intervention, Enforcement and Logistics Division) puts together a team of agents to investigate the new, the strange and the unknown around the globe, protecting the ordinary from the extraordinary.",
      popularity: 153.779,
      poster_path: "/gHUCCMy1vvj58tzE3dZqeC9SXus.jpg",
      vote_average: 7.4,
      vote_count: 2414,
    },
    {
      backdrop_path: "/qsnXwGS7KBbX4JLqHvICngtR8qg.jpg",
      first_air_date: "2015-04-10",
      genre_ids: [80, 18, 10759],
      id: 61889,
      media_type: "tv",
      name: "Marvel's Daredevil",
      origin_country: ["US"],
      original_language: "en",
      original_name: "Marvel's Daredevil",
      overview:
        "Lawyer-by-day Matt Murdock uses his heightened senses from being blinded as a young boy to fight crime at night on the streets of Hell’s Kitchen as Daredevil.",
      popularity: 68.108,
      poster_path: "/QWbPaDxiB6LW2LjASknzYBvjMj.jpg",
      vote_average: 7.9,
      vote_count: 2318,
    },
    {
      backdrop_path: "/g9ju2o4LioYYOyihBvf9lVX8XL.jpg",
      first_air_date: "2015-11-20",
      genre_ids: [10765, 18],
      id: 38472,
      media_type: "tv",
      name: "Marvel's Jessica Jones",
      origin_country: ["US"],
      original_language: "en",
      original_name: "Marvel's Jessica Jones",
      overview:
        "After a tragic ending to her short-lived super hero stint, Jessica Jones is rebuilding her personal life and career as a detective who gets pulled into cases involving people with extraordinary abilities in New York City.",
      popularity: 65.276,
      poster_path: "/wkFdanlAaV39sSXeslImfRUj3jQ.jpg",
      vote_average: 7.6,
      vote_count: 1381,
    },
    {
      backdrop_path: "/2yfmJudf695JBUJRW7QJjVN1rg5.jpg",
      first_air_date: "2017-11-17",
      genre_ids: [10759, 80, 18],
      id: 67178,
      media_type: "tv",
      name: "Marvel's The Punisher",
      origin_country: ["US"],
      original_language: "en",
      original_name: "Marvel's The Punisher",
      overview:
        "A former Marine out to punish the criminals responsible for his family's murder finds himself ensnared in a military conspiracy.",
      popularity: 63.294,
      poster_path: "/s2YM9zHF3tf2coi8t0UEzYrOHg8.jpg",
      vote_average: 8.1,
      vote_count: 1203,
    },
    {
      backdrop_path: "/ryksnIn006p7lsd83L9Za20TePv.jpg",
      first_air_date: "2015-01-06",
      genre_ids: [18],
      id: 61550,
      media_type: "tv",
      name: "Marvel's Agent Carter",
      origin_country: ["US"],
      original_language: "en",
      original_name: "Marvel's Agent Carter",
      overview:
        "It's 1946, and peace has dealt Peggy Carter a serious blow as she finds herself marginalized when the men return home from fighting abroad. Working for the covert SSR (Strategic Scientific Reserve), Peggy must balance doing administrative work and going on secret missions for Howard Stark all while trying to navigate life as a single woman in America, in the wake of losing the love of her life - Steve Rogers.",
      popularity: 62.372,
      poster_path: "/7kqIsjjDMZA5GRMH5VCdQYZJqc6.jpg",
      vote_average: 7.6,
      vote_count: 998,
    },
    {
      backdrop_path: "/7PYAUaJzzUVxS4xiJHFe338vJd1.jpg",
      first_air_date: "2017-11-21",
      genre_ids: [10759, 80, 18, 10765],
      id: 67466,
      media_type: "tv",
      name: "Marvel's Runaways",
      origin_country: ["US"],
      original_language: "en",
      original_name: "Marvel's Runaways",
      overview:
        "Every teenager thinks their parents are evil. What if you found out they actually were? Six diverse teenagers who can barely stand each other must unite against a common foe – their parents.",
      popularity: 56.189,
      poster_path: "/zceMrfO17AQkeWJZNra4O90s1vE.jpg",
      vote_average: 7.7,
      vote_count: 579,
    },
    {
      backdrop_path: "/atkOOO7Ct4qqeSx4EHWCWkFy4ns.jpg",
      first_air_date: "2017-08-19",
      genre_ids: [16, 10765],
      id: 72705,
      media_type: "tv",
      name: "Marvel's Spider-Man",
      origin_country: ["US"],
      original_language: "en",
      original_name: "Marvel's Spider-Man",
      overview:
        "An insecure but courageous and intelligent teen named Peter Parker, a new student of Midtown High, is bitten by a radioactive spider and given powers. He becomes a hero named Spider-Man after the death of his uncle and he must adapt to this new way of life.",
      popularity: 56.031,
      poster_path: "/dKdcyyHUR5WTMnrbPdYN5y9xPVp.jpg",
      vote_average: 7.8,
      vote_count: 182,
    },
    {
      backdrop_path: "/uf1BERsf5Ntkt0vIQx6Nr5owfaL.jpg",
      first_air_date: "2017-09-29",
      genre_ids: [10759, 18, 10765],
      id: 68716,
      media_type: "tv",
      name: "Marvel's Inhumans",
      origin_country: ["US"],
      original_language: "en",
      original_name: "Marvel's Inhumans",
      overview:
        "After the Royal Family of Inhumans is splintered by a military coup, they barely escape to Hawaii where their surprising interactions with the lush world and humanity around them may prove to not only save them, but Earth itself.",
      popularity: 46.77,
      poster_path: "/zKfGip55oJ9tdzhyd9ayGyFFhuo.jpg",
      vote_average: 6.1,
      vote_count: 343,
    },
    {
      backdrop_path: "/yetJ3E392yKQaG5FkHsEN7xwUrM.jpg",
      first_air_date: "2016-09-30",
      genre_ids: [18, 10765, 10759, 80],
      id: 62126,
      media_type: "tv",
      name: "Marvel's Luke Cage",
      origin_country: ["US"],
      original_language: "en",
      original_name: "Marvel's Luke Cage",
      overview:
        "Given superstrength and durability by a sabotaged experiment, a wrongly accused man escapes prison to become a superhero for hire.",
      popularity: 40.783,
      poster_path: "/quTfV803fGaSADzTeEqCbIZnt9d.jpg",
      vote_average: 7,
      vote_count: 1036,
    },
    {
      backdrop_path: null,
      first_air_date: "2021-03-12",
      genre_ids: [99],
      id: 118924,
      media_type: "tv",
      name: "Marvel Studios: Assembled",
      origin_country: ["US"],
      original_language: "en",
      original_name: "Marvel Studios: Assembled",
      overview:
        "Go behind the scenes of the shows and movies of the Marvel Cinematic Universe, following the filmmakers, cast and crew, and Marvel heroes every step of the way.",
      popularity: 39.02,
      poster_path: "/50lfJlcUuR8Nit0YSudfK59EUM7.jpg",
      vote_average: 4,
      vote_count: 1,
    },
    {
      backdrop_path: "/xHCfWGlxwbtMeeOnTvxUCZRGnkk.jpg",
      first_air_date: "2017-03-17",
      genre_ids: [10759, 18, 10765],
      id: 62127,
      media_type: "tv",
      name: "Marvel's Iron Fist",
      origin_country: ["US"],
      original_language: "en",
      original_name: "Marvel's Iron Fist",
      overview:
        "Danny Rand resurfaces 15 years after being presumed dead. Now, with the power of the Iron Fist, he seeks to reclaim his past and fulfill his destiny.",
      popularity: 35.56,
      poster_path: "/4l6KD9HhtD6nCDEfg10Lp6C6zah.jpg",
      vote_average: 6.6,
      vote_count: 1530,
    },
    {
      backdrop_path: "/7eV2vDrj1AwlTffUud66v9o0Ytq.jpg",
      first_air_date: "2017-08-18",
      genre_ids: [10765, 10759, 80],
      id: 62285,
      media_type: "tv",
      name: "Marvel's The Defenders",
      origin_country: ["US"],
      original_language: "en",
      original_name: "Marvel's The Defenders",
      overview:
        "Daredevil, Jessica Jones, Luke Cage and Iron Fist join forces to take on common enemies as a sinister conspiracy threatens New York City.",
      popularity: 34.251,
      poster_path: "/49XzINhH4LFsgz7cx6TOPcHUJUL.jpg",
      vote_average: 7.2,
      vote_count: 719,
    },
  ],
};
