export const searchData = {
  actors: [],
  movies: [
    {
      adult: false,
      backdrop_path: "/w2PMyoyLU22YvrGK3smVM9fW1jj.jpg",
      genre_ids: [28, 12, 878],
      id: 299537,
      original_language: "en",
      original_title: "Captain Marvel",
      overview:
        "The story follows Carol Danvers as she becomes one of the universe’s most powerful heroes when Earth is caught in the middle of a galactic war between two alien races. Set in the 1990s, Captain Marvel is an all-new adventure from a previously unseen period in the history of the Marvel Cinematic Universe.",
      popularity: 205.593,
      poster_path: "/AtsgWhDnHTq68L0lLsUrCnM7TjG.jpg",
      release_date: "2019-03-06",
      title: "Captain Marvel",
      video: false,
      vote_average: 7,
      vote_count: 10975,
    },
    {
      adult: false,
      backdrop_path: "/69GY219MYBurtf8joA2okEa3x8I.jpg",
      genre_ids: [99],
      id: 787923,
      original_language: "en",
      original_title: "Marvel's Behind the Mask",
      overview:
        "A documentary special that explores the power of identity behind the iconic superheroes we know and love today. These legendary Marvel creations and stories have not only reflected the world outside our window – they have become a reflection of our own identities and who we truly are.",
      popularity: 101.128,
      poster_path: "/p71YgDQk5sFHTqF3FBygLPmZEX5.jpg",
      release_date: "2021-02-12",
      title: "Marvel's Behind the Mask",
      video: false,
      vote_average: 8.3,
      vote_count: 15,
    },
    {
      adult: false,
      backdrop_path: "/iGtSJbDku0riOw1joO1qD4pGwdm.jpg",
      genre_ids: [28, 12, 878, 14, 9648],
      id: 609681,
      original_language: "en",
      original_title: "Captain Marvel 2",
      overview: "The sequel to Captain Marvel (2019).",
      popularity: 54.212,
      poster_path: "/gWxeVJ920nprJEbXbzmuuzeaAar.jpg",
      release_date: "2022-11-10",
      title: "Captain Marvel 2",
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: "/3sffou4UaLTpQHtocLBg8Egw5Uq.jpg",
      genre_ids: [878, 28, 14],
      id: 119569,
      original_language: "en",
      original_title: "Marvel One-Shot: Item 47",
      overview:
        "Benny and Claire, a down on their luck couple find a discarded Chitauri gun, referred to as 'Item 47'...",
      popularity: 28.583,
      poster_path: "/rfxvoRoZtBLUXJqLf8z9kgJWkKt.jpg",
      release_date: "2012-09-13",
      title: "Marvel One-Shot: Item 47",
      video: false,
      vote_average: 6.5,
      vote_count: 281,
    },
    {
      adult: false,
      backdrop_path: "/gpeWMh3rzbTn9auEZO6TLIzaMVl.jpg",
      genre_ids: [28, 12, 878, 14],
      id: 211387,
      original_language: "en",
      original_title: "Marvel One-Shot: Agent Carter",
      overview:
        "The film takes place one year after the events of Captain America: The First Avenger, in which Agent Carter, a member of the Strategic Scientific Reserve, is in search of the mysterious Zodiac.",
      popularity: 22.214,
      poster_path: "/5WOxsdb6uF9cDZ319Kdcru2C0eC.jpg",
      release_date: "2013-09-08",
      title: "Marvel One-Shot: Agent Carter",
      video: false,
      vote_average: 7.4,
      vote_count: 442,
    },
    {
      adult: false,
      backdrop_path: "/2qM5ZdSe8xHsqL3PWgd56hihAwY.jpg",
      genre_ids: [12, 14, 878, 28],
      id: 76122,
      original_language: "en",
      original_title: "Marvel One-Shot: The Consultant",
      overview:
        "Agent Coulson informs Agent Sitwell that the World Security Council wishes Emil Blonsky to be released from prison to join the Avengers Initiative. As Nick Fury doesn't want to release Blonsky, the two agents decide to send a patsy to sabotage the meeting...",
      popularity: 20.98,
      poster_path: "/5plg28k4bU6KH9JrZHf46cXZnzY.jpg",
      release_date: "2011-09-13",
      title: "Marvel One-Shot: The Consultant",
      video: false,
      vote_average: 6.5,
      vote_count: 278,
    },
    {
      adult: false,
      backdrop_path: "/czHz1DWWE0bcffXybT7u1wNshSx.jpg",
      genre_ids: [10770, 99],
      id: 259910,
      original_language: "en",
      original_title: "Marvel Studios: Assembling a Universe",
      overview:
        'A look at the story behind Marvel Studios and the Marvel Cinematic Universe, featuring interviews and behind-the-scenes footage from all of the Marvel films, the Marvel One-Shots and "Marvel\'s Agents of S.H.I.E.L.D."',
      popularity: 18.879,
      poster_path: "/41Ke02UzYoPsiTc3YbomPGiQKMl.jpg",
      release_date: "2014-03-18",
      title: "Marvel Studios: Assembling a Universe",
      video: false,
      vote_average: 7,
      vote_count: 105,
    },
    {
      adult: false,
      backdrop_path: "/zvjBC9guJVw32bZu4ODp6wzJ9Vi.jpg",
      genre_ids: [16],
      id: 368304,
      original_language: "en",
      original_title: "LEGO Marvel Super Heroes: Avengers Reassembled!",
      overview:
        "In \"LEGO Marvel Super Heroes: Avengers Reassembled!,\" the Avengers prepare for a party at Stark Tower and notice that Iron Man is acting strange. After some investigation, they discover that the evil Ultron has taken control of Iron Man and his armor as part of his scheme to take over the world. It's up to Captain America, the Hulk, Thor, Vision, Black Widow, Hawkeye and their friends (Spider-Man, Iron Spider, and special guest star Ant-Man) to rescue Iron Man from Ultron's clutches and defeat the super villain before he causes even more destruction and chaos.",
      popularity: 17.417,
      poster_path: "/xUBZNoY7idPfqKZepnDEv7Qc8GC.jpg",
      release_date: "2015-11-16",
      title: "LEGO Marvel Super Heroes: Avengers Reassembled!",
      video: false,
      vote_average: 6.7,
      vote_count: 58,
    },
    {
      adult: false,
      backdrop_path: "/hP6lCsOfOEQv1Mh2by79I64DBeI.jpg",
      genre_ids: [28, 12, 878, 16],
      id: 284019,
      original_language: "en",
      original_title: "Phineas and Ferb: Mission Marvel",
      overview:
        "When Dr. Doofenshmirtz's latest invention causes the Marvel heroes to lose their powers, they team up with Phineas and Ferb to save the world from Doofenshmirtz and the Marvel villains.",
      popularity: 16.066,
      poster_path: "/da2AREjdecPInHzWeZ550X1aYDU.jpg",
      release_date: "2013-08-16",
      title: "Phineas and Ferb: Mission Marvel",
      video: false,
      vote_average: 6.7,
      vote_count: 109,
    },
    {
      adult: false,
      backdrop_path: "/yoigAFjhEhJM6O6hQT9TiKH6EL7.jpg",
      genre_ids: [28, 35, 18, 14, 53],
      id: 253980,
      original_language: "en",
      original_title: "Marvel One-Shot: All Hail the King",
      overview:
        "A documentary filmmaker interviews the now-famous Trevor Slattery from behind bars.",
      popularity: 14.045,
      poster_path: "/tDpud3Y3gWtmSdcVhN0t4WiwsIK.jpg",
      release_date: "2014-02-04",
      title: "Marvel One-Shot: All Hail the King",
      video: false,
      vote_average: 6.9,
      vote_count: 263,
    },
    {
      adult: false,
      backdrop_path: "/95AKEQdhAF7YlH6XJSOFaqNTW0J.jpg",
      genre_ids: [16, 28, 35, 878, 10770, 12],
      id: 491633,
      original_language: "en",
      original_title: "Marvel Rising: Secret Warriors",
      overview:
        "When a threat no one could have expected bears down on the Marvel Universe, this ragtag, untrained band of teens have no choice but to rise together and prove to the world that sometimes the difference between a 'hero' and 'misfit' is just in the name.",
      popularity: 13.569,
      poster_path: "/kY1ufnbv2bTyoNcAtGF4BwapKi6.jpg",
      release_date: "2018-09-30",
      title: "Marvel Rising: Secret Warriors",
      video: false,
      vote_average: 6.9,
      vote_count: 56,
    },
    {
      adult: false,
      backdrop_path: "/yRbDw6Ly8MSQNDfLQNffHZuPZpS.jpg",
      genre_ids: [16, 14],
      id: 372631,
      original_language: "en",
      original_title: "Marvel Super Hero Adventures: Frost Fight!",
      overview:
        "The holiday season gets extra chilly as Loki and the frost giant Ymir plot to conquer the world. Marvel heroes Iron Man, Captain America, Hulk, Thor and others must stop the villains from stealing Santa's power – if anyone can actually find the mysterious Mr. Claus. Fortunately, Rocket Raccoon and Groot are also hot on Santa's trail. Heroes, villains, elves and cosmic bounty hunters collide in an epic quest that leaves the fate of the holiday and the world in the balance.",
      popularity: 12.919,
      poster_path: "/2StM8Vavf7ukvuj9mxg1o7nKxmi.jpg",
      release_date: "2015-12-15",
      title: "Marvel Super Hero Adventures: Frost Fight!",
      video: true,
      vote_average: 6,
      vote_count: 31,
    },
    {
      adult: false,
      backdrop_path: "/vp4PvW8vxWHN8rai42SeOXcimcp.jpg",
      genre_ids: [16, 878, 28],
      id: 583209,
      original_language: "en",
      original_title: "Marvel Rising: Heart of Iron",
      overview:
        "Ironheart, AKA Riri Williams, is having difficulty adjusting to college life as the youngest student there when the college's engineering lab is demolished by an alien and her best friend is kidnapped. Inspired by Iron Man, she develops a plan to save her friend.",
      popularity: 10.734,
      poster_path: "/z3lD286jY8iYasC5hJZ2kgZF9uY.jpg",
      release_date: "2019-04-03",
      title: "Marvel Rising: Heart of Iron",
      video: false,
      vote_average: 7.6,
      vote_count: 37,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [35, 18],
      id: 278755,
      original_language: "en",
      original_title: "Maggie Marvel",
      overview:
        "About a single Mom who moonlights as a contract killer. Maggie Marvel must balance career and family, murder and math homework. She is pushed into this dangerous world... only to find out she is very good at it.",
      popularity: 9.226,
      poster_path: null,
      release_date: "2011-03-05",
      title: "Maggie Marvel",
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: "/4oQo2pkNyv5zOqwAdwI2dSJTmEx.jpg",
      genre_ids: [16, 28, 12],
      id: 592689,
      original_language: "en",
      original_title: "Marvel Rising: Playing with Fire",
      overview:
        "Inferno’s powers are stolen by a young and powerful villain and it’s up to the Secret Warriors to defeat their new foe and help their friend. But does Inferno even WANT his powers back? Meanwhile, America Chavez learns a lesson about friendship and family from teammate Ms. Marvel.",
      popularity: 8.554,
      poster_path: "/lelNkBnjIi4N1uQBV2TnODgS9UT.jpg",
      release_date: "2019-12-18",
      title: "Marvel Rising: Playing with Fire",
      video: false,
      vote_average: 6.7,
      vote_count: 24,
    },
    {
      adult: false,
      backdrop_path: "/EXJrCRBYAPffNuMQbX7irsbrRn.jpg",
      genre_ids: [16, 28],
      id: 622230,
      original_language: "en",
      original_title: "LEGO Marvel Spider-Man: Vexed By Venom",
      overview:
        "Thanks to Green Goblin and Venom, tech theft is now at an all-time high -- can our Friendly Neighborhood Spider-Man put an end to their mysterious villainous scheme before all of New York City is destroyed?",
      popularity: 8.474,
      poster_path: "/gTo2r8nNU3ZYAS6DqdeSp1VEqkq.jpg",
      release_date: "2019-08-03",
      title: "LEGO Marvel Spider-Man: Vexed By Venom",
      video: false,
      vote_average: 7.3,
      vote_count: 6,
    },
    {
      adult: false,
      backdrop_path: "/p056WP3fMnEcSSYhiN1kV9AyNZW.jpg",
      genre_ids: [16, 28, 35, 878],
      id: 592687,
      original_language: "en",
      original_title: "Marvel Rising: Battle of the Bands",
      overview:
        "On the day of Gwen’s “Battle of the Bands” competition, mysterious attacks force her and the Secret Warriors to investigate. Can they save the city and get Gwen to the concert on time?",
      popularity: 8.292,
      poster_path: "/mFL0EzAhEj3vscyGUMk6sT7pfQg.jpg",
      release_date: "2019-08-28",
      title: "Marvel Rising: Battle of the Bands",
      video: false,
      vote_average: 7.3,
      vote_count: 22,
    },
    {
      adult: false,
      backdrop_path: "/Jg4SNkNlYJXOJVo2TntrA5M2Kg.jpg",
      genre_ids: [16, 28, 12],
      id: 576743,
      original_language: "en",
      original_title: "Marvel Rising: Chasing Ghosts",
      overview:
        "Hot on the trails of Sheath and Exile, Ghost-Spider teams up with the rest of the Secret Warriors to bring down the villains for good.",
      popularity: 7.735,
      poster_path: "/pufQvXrrxng95dT4kYlQtXn98kK.jpg",
      release_date: "2019-01-16",
      title: "Marvel Rising: Chasing Ghosts",
      video: false,
      vote_average: 7.4,
      vote_count: 22,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [99],
      id: 441917,
      original_language: "en",
      original_title: "The Marvel Universe Expands: Marvel 75th Anniversary",
      overview: "A documentary about some of Marvel's most famous characters.",
      popularity: 7.173,
      poster_path: "/2faGI0USP1JG9OuLdFZw1M7lwhF.jpg",
      release_date: "2014-08-21",
      title: "The Marvel Universe Expands: Marvel 75th Anniversary",
      video: false,
      vote_average: 7.5,
      vote_count: 2,
    },
    {
      adult: false,
      backdrop_path: "/dkWcUCrXFTotX4VoIguEVC511dh.jpg",
      genre_ids: [14, 28, 878, 10751],
      id: 61020,
      original_language: "en",
      original_title: "Adventures of Captain Marvel",
      overview:
        "On a scientific expedition to Siam young Billy Batson is given the ability to change himself into the super-powered Captain Marvel by the wizard Shazam, who tells him his powers will last only as long as the Golden Scorpion idol is threatened. Finding the idol, the scientists realize it could be the most powerful weapon in the world and remove the lenses that energize it, distributing them among themselves so that no one would be able to use the idol by himself. Back in the US, Billy Batson, as Captain Marvel, wages a battle against an evil, hooded figure, the Scorpion, who hopes to accumulate all five lenses, thereby gaining control of the super-powerful weapon",
      popularity: 6.379,
      poster_path: "/oOQIcNcFbZdTUSWFmY1GRz0xCT5.jpg",
      release_date: "1941-03-28",
      title: "Adventures of Captain Marvel",
      video: false,
      vote_average: 6.2,
      vote_count: 17,
    },
  ],
  shows: [],
};

export const locationData = {
  pathname: "/search",
  search: "?query=marvel&options=movie",
  hash: "",
  key: "peom3k",
};
