export const detailData = {
  adult: false,
  backdrop_path: "/w2PMyoyLU22YvrGK3smVM9fW1jj.jpg",
  belongs_to_collection: {
    id: 623911,
    name: "Captain Marvel Collection",
    poster_path: "/4diELSzXT1FbN782cOogEWeKN2w.jpg",
    backdrop_path: "/ubZUKycnQldt2umj0bPD2VwXDJM.jpg",
  },
  budget: 152000000,
  genres: [
    {
      id: 28,
      name: "Action",
    },
    {
      id: 12,
      name: "Adventure",
    },
    {
      id: 878,
      name: "Science Fiction",
    },
  ],
  homepage: "https://www.marvel.com/movies/captain-marvel",
  id: 299537,
  imdb_id: "tt4154664",
  original_language: "en",
  original_title: "Captain Marvel",
  overview:
    "The story follows Carol Danvers as she becomes one of the universe’s most powerful heroes when Earth is caught in the middle of a galactic war between two alien races. Set in the 1990s, Captain Marvel is an all-new adventure from a previously unseen period in the history of the Marvel Cinematic Universe.",
  popularity: 205.461,
  poster_path: "/AtsgWhDnHTq68L0lLsUrCnM7TjG.jpg",
  production_companies: [
    {
      id: 420,
      logo_path: "/hUzeosd33nzE5MCNsZxCGEKTXaQ.png",
      name: "Marvel Studios",
      origin_country: "US",
    },
  ],
  production_countries: [
    {
      iso_3166_1: "US",
      name: "United States of America",
    },
  ],
  release_date: "2019-03-06",
  revenue: 1128276090,
  runtime: 124,
  spoken_languages: [
    {
      english_name: "English",
      iso_639_1: "en",
      name: "English",
    },
  ],
  status: "Released",
  tagline: "Higher. Further. Faster.",
  title: "Captain Marvel",
  video: false,
  vote_average: 7,
  vote_count: 10975,
  credits: {
    cast: [
      {
        adult: false,
        gender: 1,
        id: 60073,
        known_for_department: "Acting",
        name: "Brie Larson",
        original_name: "Brie Larson",
        popularity: 18.134,
        profile_path: "/nTABNG8Sw4EVN3xodn2JBdEmBqv.jpg",
        cast_id: 140,
        character: "Carol Danvers / Vers / Captain Marvel",
        credit_id: "5c86e37f0e0a264310683e5a",
        order: 0,
      },
      {
        adult: false,
        gender: 2,
        id: 2231,
        known_for_department: "Acting",
        name: "Samuel L. Jackson",
        original_name: "Samuel L. Jackson",
        popularity: 12.627,
        profile_path: "/mXN4Gw9tZJVKrLJHde2IcUHmV3P.jpg",
        cast_id: 74,
        character: "Nick Fury",
        credit_id: "5c408274c3a368216241b744",
        order: 1,
      },
      {
        adult: false,
        gender: 2,
        id: 77335,
        known_for_department: "Acting",
        name: "Ben Mendelsohn",
        original_name: "Ben Mendelsohn",
        popularity: 9.109,
        profile_path: "/qSPMGYN0TtVKD5QyyV7fCyzL2sU.jpg",
        cast_id: 78,
        character: "Talos / Keller",
        credit_id: "5c4082b8c3a368216241b76e",
        order: 2,
      },
      {
        adult: false,
        gender: 2,
        id: 9642,
        known_for_department: "Acting",
        name: "Jude Law",
        original_name: "Jude Law",
        popularity: 13.605,
        profile_path: "/A6Y0m7qEe04ZTHKyYDLbnyCHNzn.jpg",
        cast_id: 77,
        character: "Yon-Rogg",
        credit_id: "5c4082a30e0a2615549077ba",
        order: 3,
      },
      {
        adult: false,
        gender: 1,
        id: 516,
        known_for_department: "Acting",
        name: "Annette Bening",
        original_name: "Annette Bening",
        popularity: 5.621,
        profile_path: "/bs4hB5t2mHMn6C2ZGOlP5LfSEPe.jpg",
        cast_id: 106,
        character: "Supreme Intelligence / Dr. Wendy Lawson",
        credit_id: "5c6da2970e0a262c99a10e7e",
        order: 4,
      },
      {
        adult: false,
        gender: 2,
        id: 938,
        known_for_department: "Acting",
        name: "Djimon Hounsou",
        original_name: "Djimon Hounsou",
        popularity: 7.6,
        profile_path: "/hco0KMbrxACYTmBfAkSzCf23CXV.jpg",
        cast_id: 80,
        character: "Korath",
        credit_id: "5c4082d5c3a368694e41ad29",
        order: 5,
      },
      {
        adult: false,
        gender: 2,
        id: 72095,
        known_for_department: "Acting",
        name: "Lee Pace",
        original_name: "Lee Pace",
        popularity: 7.958,
        profile_path: "/8DVo5jbEmYpKPrhIFHkA7gGs1X8.jpg",
        cast_id: 76,
        character: "Ronan the Accuser",
        credit_id: "5c4082950e0a263867920237",
        order: 6,
      },
      {
        adult: false,
        gender: 1,
        id: 1360281,
        known_for_department: "Acting",
        name: "Lashana Lynch",
        original_name: "Lashana Lynch",
        popularity: 2.196,
        profile_path: "/9bThcInfgzeXFk1Uicy2773Zul0.jpg",
        cast_id: 87,
        character: "Maria Rambeau",
        credit_id: "5c40833cc3a368694e41ae49",
        order: 7,
      },
      {
        adult: false,
        gender: 1,
        id: 97576,
        known_for_department: "Acting",
        name: "Gemma Chan",
        original_name: "Gemma Chan",
        popularity: 13.521,
        profile_path: "/r5yu8cnSaVA36j0CTSC8TjiYYE5.jpg",
        cast_id: 75,
        character: "Minn-Erva",
        credit_id: "5c408284c3a36811b4411df1",
        order: 8,
      },
      {
        adult: false,
        gender: 2,
        id: 9048,
        known_for_department: "Acting",
        name: "Clark Gregg",
        original_name: "Clark Gregg",
        popularity: 7.418,
        profile_path: "/zwyhwrxgpiufSPpjC9dxCy5kAB0.jpg",
        cast_id: 82,
        character: "Agent Phil Coulson",
        credit_id: "5c4082fb9251416e06b078bd",
        order: 9,
      },
      {
        adult: false,
        gender: 2,
        id: 76618,
        known_for_department: "Acting",
        name: "Rune Temte",
        original_name: "Rune Temte",
        popularity: 1.834,
        profile_path: "/6vfrlTNDyHhMgzFMzmg0IbOmHM2.jpg",
        cast_id: 81,
        character: "Bron-Charr",
        credit_id: "5c4082e50e0a2654c1921ce6",
        order: 10,
      },
      {
        adult: false,
        gender: 0,
        id: 86381,
        known_for_department: "Acting",
        name: "Algenis Perez Soto",
        original_name: "Algenis Perez Soto",
        popularity: 0.766,
        profile_path: "/pUCNFbXpXuEelbrbiOo52vG3daa.jpg",
        cast_id: 110,
        character: "Att-Lass",
        credit_id: "5c7f6fb60e0a2643055bbbdc",
        order: 11,
      },
      {
        adult: false,
        gender: 1,
        id: 1172108,
        known_for_department: "Acting",
        name: "Mckenna Grace",
        original_name: "Mckenna Grace",
        popularity: 8.388,
        profile_path: "/jQLBM6ErQnvU8QqNvW8KKF9y8N0.jpg",
        cast_id: 79,
        character: "Young Carol (13 Years Old)",
        credit_id: "5c4082c60e0a2654c1921cd6",
        order: 12,
      },
      {
        adult: false,
        gender: 1,
        id: 2258733,
        known_for_department: "Acting",
        name: "Akira Akbar",
        original_name: "Akira Akbar",
        popularity: 1.588,
        profile_path: "/zJ6IndgsiMHaM36jZfIBJZwzT5u.jpg",
        cast_id: 112,
        character: "Monica Rambeau (11 Years Old)",
        credit_id: "5c7f70220e0a2642fe5bf53f",
        order: 13,
      },
      {
        adult: false,
        gender: 2,
        id: 1232599,
        known_for_department: "Acting",
        name: "Matthew Maher",
        original_name: "Matthew Maher",
        popularity: 4.765,
        profile_path: "/nO9Yhz7ERzATcHploljXgR4cAq.jpg",
        cast_id: 93,
        character: "Norex",
        credit_id: "5c4083e10e0a2638679204fe",
        order: 14,
      },
      {
        adult: false,
        gender: 2,
        id: 1610710,
        known_for_department: "Acting",
        name: "Chuku Modu",
        original_name: "Chuku Modu",
        popularity: 6.675,
        profile_path: "/taoknxCAJcuzn71YKbCqc4hsYyR.jpg",
        cast_id: 111,
        character: "Soh-Larr",
        credit_id: "5c7f6fd99251412760185431",
        order: 15,
      },
      {
        adult: false,
        gender: 2,
        id: 6623,
        known_for_department: "Acting",
        name: "Vik Sahay",
        original_name: "Vik Sahay",
        popularity: 3.237,
        profile_path: "/690bPfmzaXsrZ1eDcUOCDT5TPpq.jpg",
        cast_id: 115,
        character: "Hero Torfan",
        credit_id: "5c7f7156c3a3684e98d33369",
        order: 16,
      },
      {
        adult: false,
        gender: 2,
        id: 74539,
        known_for_department: "Acting",
        name: "Colin Ford",
        original_name: "Colin Ford",
        popularity: 4.158,
        profile_path: "/AquXBhH1jXdObhU1Fw3ecITEBVW.jpg",
        cast_id: 114,
        character: "Steve Danvers",
        credit_id: "5c7f7119925141277a1867a8",
        order: 17,
      },
      {
        adult: false,
        gender: 2,
        id: 28868,
        known_for_department: "Acting",
        name: "Kenneth Mitchell",
        original_name: "Kenneth Mitchell",
        popularity: 2.078,
        profile_path: "/8p9WeJZk3acU6QEBgJHgMKrr5kQ.jpg",
        cast_id: 86,
        character: "Joseph Danvers",
        credit_id: "5c40832f9251415318b06865",
        order: 18,
      },
      {
        adult: false,
        gender: 2,
        id: 1514930,
        known_for_department: "Acting",
        name: "Stephen A. Chang",
        original_name: "Stephen A. Chang",
        popularity: 1.116,
        profile_path: "/gZxyFXDPDrZBAHqBXyujoYaW6Hn.jpg",
        cast_id: 141,
        character: "Cadet Officer",
        credit_id: "5cbb19e99251417d39f5ab1d",
        order: 19,
      },
      {
        adult: false,
        gender: 2,
        id: 1163622,
        known_for_department: "Acting",
        name: "Pete Ploszek",
        original_name: "Pete Ploszek",
        popularity: 2.572,
        profile_path: "/g0b5aePXb1IXgl7177BGDROe8IV.jpg",
        cast_id: 90,
        character: "Bret Johnson",
        credit_id: "5c4083719251416e06b0797f",
        order: 20,
      },
      {
        adult: false,
        gender: 1,
        id: 2175390,
        known_for_department: "Acting",
        name: "London Fuller",
        original_name: "London Fuller",
        popularity: 1.96,
        profile_path: "/i8f3yFO82g2KXcl5CZySxcZcwlk.jpg",
        cast_id: 95,
        character: "Young Carol (6 Years Old)",
        credit_id: "5c408401c3a368694e41af1d",
        order: 21,
      },
      {
        adult: false,
        gender: 1,
        id: 2292715,
        known_for_department: "Acting",
        name: "Azari Akbar",
        original_name: "Azari Akbar",
        popularity: 1.105,
        profile_path: "/2J424EHoWH1RQfAAxFN79FlbTi9.jpg",
        cast_id: 147,
        character: "Monica Rambeau (5 Years Old)",
        credit_id: "5cbb1d149251412577f49b56",
        order: 22,
      },
      {
        adult: false,
        gender: 2,
        id: 1183671,
        known_for_department: "Acting",
        name: "Mark Daugherty",
        original_name: "Mark Daugherty",
        popularity: 1.38,
        profile_path: "/iRfLeThcGyQ14IbX1C8Fvak9zYs.jpg",
        cast_id: 117,
        character: "Skrull Main Tech",
        credit_id: "5c7f7259c3a3684e92d39115",
        order: 23,
      },
      {
        adult: false,
        gender: 1,
        id: 1288264,
        known_for_department: "Acting",
        name: "Diana Toshiko",
        original_name: "Diana Toshiko",
        popularity: 1.4,
        profile_path: "/pBQwfWbSUhtKH6gXQcHXJu7PS4e.jpg",
        cast_id: 142,
        character: "Skrull Tech #1",
        credit_id: "5cbb1a12925141097df5a0f7",
        order: 24,
      },
      {
        adult: false,
        gender: 2,
        id: 2293121,
        known_for_department: "Acting",
        name: "Barry Curtis",
        original_name: "Barry Curtis",
        popularity: 1.38,
        profile_path: "/cvy6VCnSKxWO2K9NtjjNnTjQCFW.jpg",
        cast_id: 148,
        character: "Mall Security Guard",
        credit_id: "5cbbbf6b9251412577f57c19",
        order: 25,
      },
      {
        adult: false,
        gender: 1,
        id: 2219719,
        known_for_department: "Acting",
        name: "Emily Ozrey",
        original_name: "Emily Ozrey",
        popularity: 1.96,
        profile_path: "/lzsDy3qCZfe71dlNy2O0Yoyogld.jpg",
        cast_id: 94,
        character: "Surfer Girl Talos #1",
        credit_id: "5c4083f10e0a2646a291aaa4",
        order: 26,
      },
      {
        adult: false,
        gender: 1,
        id: 1989352,
        known_for_department: "Acting",
        name: "Abigaille Ozrey",
        original_name: "Abigaille Ozrey",
        popularity: 0.6,
        profile_path: null,
        cast_id: 91,
        character: "Surfer Girl Talos #2",
        credit_id: "5c40837f9251416b02b0b46e",
        order: 27,
      },
      {
        adult: false,
        gender: 1,
        id: 149776,
        known_for_department: "Acting",
        name: "Marilyn Brett",
        original_name: "Marilyn Brett",
        popularity: 2.188,
        profile_path: "/hECTt6xg2Le2iYTyFCe2M3pBhs.jpg",
        cast_id: 92,
        character: "Older Lady on Train",
        credit_id: "5c4083d3c3a368638a41d62f",
        order: 28,
      },
      {
        adult: false,
        gender: 2,
        id: 7624,
        known_for_department: "Writing",
        name: "Stan Lee",
        original_name: "Stan Lee",
        popularity: 9.282,
        profile_path: "/nGjBAc25C3LT23NqeOfY1pCcax8.jpg",
        cast_id: 113,
        character: "Stan Lee",
        credit_id: "5c7f7108c3a3684e98d3331f",
        order: 29,
      },
      {
        adult: false,
        gender: 2,
        id: 1038379,
        known_for_department: "Acting",
        name: "Robert Kazinsky",
        original_name: "Robert Kazinsky",
        popularity: 1.16,
        profile_path: "/u9MCG0KgTyCgpiV5qmMr5gIvglU.jpg",
        cast_id: 83,
        character: "Biker (The Don)",
        credit_id: "5c4083090e0a2646a291a8db",
        order: 30,
      },
      {
        adult: false,
        gender: 2,
        id: 88928,
        known_for_department: "Acting",
        name: "Nelson Franklin",
        original_name: "Nelson Franklin",
        popularity: 1.611,
        profile_path: "/2YYnTxpFmS5i9qRkb6H4Nxky2px.jpg",
        cast_id: 138,
        character: "Medical Examiner",
        credit_id: "5c7fd0a6925141276018b2fc",
        order: 31,
      },
      {
        adult: false,
        gender: 2,
        id: 76022,
        known_for_department: "Acting",
        name: "Patrick Brennan",
        original_name: "Patrick Brennan",
        popularity: 1.078,
        profile_path: "/dEJbh3gfwYMg5q0vdCpx9l3cMmh.jpg",
        cast_id: 144,
        character: "Bartender",
        credit_id: "5cbb1a840e0a266b96f510b2",
        order: 32,
      },
      {
        adult: false,
        gender: 2,
        id: 17837,
        known_for_department: "Acting",
        name: "Patrick Gallagher",
        original_name: "Patrick Gallagher",
        popularity: 1.919,
        profile_path: "/8ZWcp7kRwoh5cGZFByDQdhTODw9.jpg",
        cast_id: 139,
        character: "Security Chief",
        credit_id: "5c7fd3a10e0a2643015c4b55",
        order: 33,
      },
      {
        adult: false,
        gender: 1,
        id: 1077805,
        known_for_department: "Acting",
        name: "Ana Ayora",
        original_name: "Ana Ayora",
        popularity: 2.623,
        profile_path: "/6mo946WfFCeCvHFjglr00nDI4KD.jpg",
        cast_id: 107,
        character: "Agent Whitcher",
        credit_id: "5c7ba119c3a3681c4b1ac546",
        order: 34,
      },
      {
        adult: false,
        gender: 0,
        id: 2325804,
        known_for_department: "Acting",
        name: "Lyonetta Flowers",
        original_name: "Lyonetta Flowers",
        popularity: 0.6,
        profile_path: null,
        cast_id: 150,
        character: "Monica's Grandmother",
        credit_id: "5cf0811192514141f2b837df",
        order: 35,
      },
      {
        adult: false,
        gender: 0,
        id: 2325805,
        known_for_department: "Acting",
        name: "Rufus Flowers",
        original_name: "Rufus Flowers",
        popularity: 0.98,
        profile_path: null,
        cast_id: 151,
        character: "Monica's Grandfather",
        credit_id: "5cf081340e0a2670cec993c8",
        order: 36,
      },
      {
        adult: false,
        gender: 1,
        id: 2292713,
        known_for_department: "Acting",
        name: "Sharon Blynn",
        original_name: "Sharon Blynn",
        popularity: 0.6,
        profile_path: "/m3lzrdrNc0lleW9Tva64flZ8Fah.jpg",
        cast_id: 146,
        character: "Soren",
        credit_id: "5cbb1c470e0a267e34ee8bcb",
        order: 37,
      },
      {
        adult: false,
        gender: 1,
        id: 2325807,
        known_for_department: "Acting",
        name: "Auden L. Ophuls",
        original_name: "Auden L. Ophuls",
        popularity: 0.6,
        profile_path: "/jJ6CqPbwg78k3NBlk9Z3QAwVjQs.jpg",
        cast_id: 152,
        character: "Talos' Daughter",
        credit_id: "5cf081a2925141247cb82eea",
        order: 38,
      },
      {
        adult: false,
        gender: 1,
        id: 2325808,
        known_for_department: "Acting",
        name: "Harriet L. Ophuls",
        original_name: "Harriet L. Ophuls",
        popularity: 0.6,
        profile_path: "/21hkUZE99Nff7G4PPr2jIPE2cnY.jpg",
        cast_id: 153,
        character: "Talos' Daughter",
        credit_id: "5cf081d30e0a264876c994dd",
        order: 39,
      },
      {
        adult: false,
        gender: 2,
        id: 583885,
        known_for_department: "Acting",
        name: "Matthew Bellows",
        original_name: "Matthew Bellows",
        popularity: 1.263,
        profile_path: "/wwe7XA8v0iBsJykUPqsVoJsz0WV.jpg",
        cast_id: 118,
        character: "Accuser #1",
        credit_id: "5c7f729dc3a3684e89d37d78",
        order: 40,
      },
      {
        adult: false,
        gender: 2,
        id: 1523304,
        known_for_department: "Acting",
        name: "Richard Zeringue",
        original_name: "Richard Zeringue",
        popularity: 0.766,
        profile_path: "/hWDoncFVG2PuE09b7rJ8fL5dvtH.jpg",
        cast_id: 116,
        character: "Tom the Neighbor",
        credit_id: "5c7f71850e0a2643015bdf82",
        order: 41,
      },
      {
        adult: false,
        gender: 2,
        id: 1240417,
        known_for_department: "Acting",
        name: "Duane Henry",
        original_name: "Duane Henry",
        popularity: 0.97,
        profile_path: "/mnYq3tMHrn5vnWFyMTVS2L5NrpU.jpg",
        cast_id: 145,
        character: "Talos-Kree Soldier",
        credit_id: "5cbb1ad40e0a2641edef22ea",
        order: 42,
      },
      {
        adult: false,
        gender: 2,
        id: 16828,
        known_for_department: "Acting",
        name: "Chris Evans",
        original_name: "Chris Evans",
        popularity: 18.276,
        profile_path: "/3bOGNsHlrswhyW79uvIHH1V43JI.jpg",
        cast_id: 134,
        character: "Steve Rogers / Captain America (uncredited)",
        credit_id: "5c7f8bfb0e0a2642fe5c15f9",
        order: 43,
      },
      {
        adult: false,
        gender: 1,
        id: 1245,
        known_for_department: "Acting",
        name: "Scarlett Johansson",
        original_name: "Scarlett Johansson",
        popularity: 54.09,
        profile_path: "/6NsMbJXRlDZuDzatN2akFdGuTvx.jpg",
        cast_id: 135,
        character: "Natasha Romanoff / Black Widow (uncredited)",
        credit_id: "5c7f8c1992514127691885af",
        order: 44,
      },
      {
        adult: false,
        gender: 2,
        id: 1896,
        known_for_department: "Acting",
        name: "Don Cheadle",
        original_name: "Don Cheadle",
        popularity: 8.514,
        profile_path: "/b1EVJWdFn7a75qVYJgwO87W2TJU.jpg",
        cast_id: 137,
        character: "James 'Rhodey' Rhodes / War Machine (uncredited)",
        credit_id: "5c7f8c3fc3a3684e9dd38652",
        order: 45,
      },
      {
        adult: false,
        gender: 2,
        id: 103,
        known_for_department: "Acting",
        name: "Mark Ruffalo",
        original_name: "Mark Ruffalo",
        popularity: 11.504,
        profile_path: "/5GilHMOt5PAQh6rlUKZzGmaKEI7.jpg",
        cast_id: 136,
        character: "Bruce Banner / The Hulk (uncredited)",
        credit_id: "5c7f8c30c3a3684e89d394c6",
        order: 46,
      },
      {
        adult: false,
        gender: 0,
        id: 2467593,
        known_for_department: "Acting",
        name: "Matthew 'Spider' Kimmel",
        original_name: "Matthew 'Spider' Kimmel",
        popularity: 0.728,
        profile_path: "/k2sFueAGJolebw9uumetMLM2lte.jpg",
        cast_id: 227,
        character: "Spider",
        credit_id: "5ddc3af0a80673001411f75c",
        order: 47,
      },
      {
        adult: false,
        gender: 2,
        id: 2467594,
        known_for_department: "Acting",
        name: "Stephen 'Cajun' Del Bagno",
        original_name: "Stephen 'Cajun' Del Bagno",
        popularity: 0.6,
        profile_path: "/4OyBs3wfIy5lDvA6T23CVyUDUFW.jpg",
        cast_id: 228,
        character: "Cajun",
        credit_id: "5ddc3aff3faba0001300f823",
        order: 48,
      },
      {
        adult: false,
        gender: 1,
        id: 2518232,
        known_for_department: "Writing",
        name: "Kelly Sue DeConnick",
        original_name: "Kelly Sue DeConnick",
        popularity: 1.38,
        profile_path: "/q9VLVEVCRVLyoMqJZL2UJip2228.jpg",
        cast_id: 229,
        character: "Lady in Subway Station (uncredited)",
        credit_id: "5e29036a4ca676001742b8df",
        order: 49,
      },
      {
        adult: false,
        gender: 2,
        id: 2323834,
        known_for_department: "Acting",
        name: "Vinny O'Brien",
        original_name: "Vinny O'Brien",
        popularity: 0.6,
        profile_path: "/7N0xG2bvAXtJX4BOr4Djl92T1FI.jpg",
        cast_id: 232,
        character: "Skrull Spy 2 (uncredited)",
        credit_id: "5eda646821c4ca0021e8b63c",
        order: 50,
      },
    ],
  },
};
